// <auto-generated />
using System;
using BankAccountForm.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankAccountForm.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20240606180159_mig-1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankAccountForm.Entities.Accounts.BankCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("CardTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2029, 6, 6, 22, 1, 58, 634, DateTimeKind.Local).AddTicks(9255));

                    b.HasKey("Id");

                    b.HasIndex("CardTypeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("BankCards");
                });

            modelBuilder.Entity("BankAccountForm.Entities.Accounts.CardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CardTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Debet"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Credit"
                        });
                });

            modelBuilder.Entity("BankAccountForm.Entities.Accounts.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("BankCardId")
                        .HasColumnType("int");

                    b.Property<float>("Percent")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BankCardId")
                        .IsUnique();

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("BankAccountForm.Entities.Accounts.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BankAccountForm.Entities.Accounts.CustomerWorkDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerWorkDetails");
                });

            modelBuilder.Entity("BankAccountForm.Entities.Accounts.BankCard", b =>
                {
                    b.HasOne("BankAccountForm.Entities.Accounts.CardType", "CardType")
                        .WithMany("BankCards")
                        .HasForeignKey("CardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankAccountForm.Entities.Accounts.Customer", "Customer")
                        .WithMany("BankCards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardType");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BankAccountForm.Entities.Accounts.Credit", b =>
                {
                    b.HasOne("BankAccountForm.Entities.Accounts.BankCard", "BankCard")
                        .WithOne("Credit")
                        .HasForeignKey("BankAccountForm.Entities.Accounts.Credit", "BankCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankCard");
                });

            modelBuilder.Entity("BankAccountForm.Entities.Accounts.CustomerWorkDetail", b =>
                {
                    b.HasOne("BankAccountForm.Entities.Accounts.Customer", "Customer")
                        .WithOne("CustomerWorkDetail")
                        .HasForeignKey("BankAccountForm.Entities.Accounts.CustomerWorkDetail", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BankAccountForm.Entities.Accounts.BankCard", b =>
                {
                    b.Navigation("Credit")
                        .IsRequired();
                });

            modelBuilder.Entity("BankAccountForm.Entities.Accounts.CardType", b =>
                {
                    b.Navigation("BankCards");
                });

            modelBuilder.Entity("BankAccountForm.Entities.Accounts.Customer", b =>
                {
                    b.Navigation("BankCards");

                    b.Navigation("CustomerWorkDetail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
